cart/urls.py
from django.conf.urls import url
from cart import views

app_name = 'cart'
urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

cosmetic/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import logout_then_login
from django.urls import path, include

from cosmetic import views
from cosmetic.views import HomePage
from retail import settings

app_name = 'cosmetic'
urlpatterns = [
    url('^$', HomePage.as_view(), name='home_page'),
    # url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    # url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
    url(r'^(?P<category_slug>[-\w]+)/(?P<slug>[-\w]+)/$', views.ProductView.as_view(), name='product_detail'),
    url(r'^login', views.Login.as_view(), name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

retail/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from retail import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    path('', include('social_django.urls')),
    url(r'^', include('cosmetic.urls', namespace='cosmetic')),
    path('summernote/', include('django_summernote.urls')),  # django_summernote URLS
]
urlpatterns  += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cosmetic/models.py
from django.db import models
from taggit.managers import TaggableManager
from django.conf import settings
# Create your models here.

app_name = 'cosmetic'

def category_picture_directory_path(instance, filename):
    return 'images/category/{0}/{1}'.format(instance.slug, filename)


def product_picture_directory_path(instance, filename):
    return 'images/products/{0}/{1}'.format(instance.slug, filename)


class UserProfile(models.Model):
    class Meta:
        verbose_name = 'Профиль пользователя'
        verbose_name_plural = 'Профиль пользователей'

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True, related_name='user_profile', verbose_name='Профиль пользователя')
    middle_name = models.CharField(max_length=64, verbose_name='Отчество', blank=True, null=True)
    phone = models.CharField(verbose_name='Номер телефона', max_length=32, blank=True, null=True)

    def __repr__(self):
        return '{} {} {}'.format(self.user.email, self.user.last_name, self.user.first_name)

class Category(models.Model):
    class Meta:
        verbose_name = 'Категория товара'
        verbose_name_plural = 'Категории товаров'

    category_product = models.CharField(verbose_name='Категория продукта', max_length=100)
    index = models.SmallIntegerField(verbose_name='Порядковый номер', default=1)
    slug = models.SlugField(verbose_name='Адрес страницы Slug')
    image = models.FileField(upload_to=category_picture_directory_path, verbose_name='Изображение')
    created = models.DateTimeField(auto_now=False, auto_now_add=True, verbose_name='Дата создания')
    changed = models.DateTimeField(auto_now=True, auto_now_add=False, verbose_name='Дата редактирования')

    def __str__(self):
        return self.category_product

class Product(models.Model):
    class Meta:
        verbose_name = 'Карточка продукта'
        verbose_name_plural = 'Карточки продуктов'

    name = models.CharField(verbose_name='Наименование продукта', max_length=250)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, verbose_name='Категория товара',
                                 related_name='all_product')
    slug = models.SlugField(verbose_name='Адрес страницы Slug')
    brand = models.CharField(verbose_name='Бренд', max_length=200)
    country = models.CharField(verbose_name='Страна производитель', max_length=200)
    manufacturer = models.CharField(verbose_name='Производитель', max_length=200)
    size = models.CharField(verbose_name='объем', max_length=200)
    method_of_application = models.TextField(verbose_name='Способ применения')
    description = models.TextField(verbose_name='Описание товара')
    status = models.CharField(verbose_name='Статус продукта', max_length=100, blank=True, null=True,choices=(
        ('new','Новинка'),
        ('hot','Популярная'),
        ('sale','Распродажа')
    ))
    image_1 = models.FileField(upload_to=product_picture_directory_path, verbose_name='Изображение 1')
    image_2 = models.FileField(upload_to=product_picture_directory_path, verbose_name='Изображение 2', blank=True, null=True)
    image_3 = models.FileField(upload_to=product_picture_directory_path, verbose_name='Изображение 3', blank=True, null=True)
    image_4 = models.FileField(upload_to=product_picture_directory_path, verbose_name='Изображение 4', blank=True, null=True)
    image_5 = models.FileField(upload_to=product_picture_directory_path, verbose_name='Изображение 5', blank=True, null=True)
    image_6 = models.FileField(upload_to=product_picture_directory_path, verbose_name='Изображение 6', blank=True, null=True)
    current_price = models.DecimalField(verbose_name='Текущая цена продукта', max_digits=32, decimal_places=2)
    sale_price = models.DecimalField(verbose_name='Акционная цена', max_digits=32, decimal_places=2, blank=True, null=True)
    end_sale = models.DateTimeField(verbose_name='Окончание акционной цены', blank=True, null=True)
    number_sold = models.IntegerField(verbose_name='Количество проданных', default=0)
    number_in_stock = models.IntegerField(verbose_name='Количество на складе', default=0)

    tags = TaggableManager()
    created = models.DateTimeField(auto_now=False, auto_now_add=True, verbose_name='Дата создания')
    changed = models.DateTimeField(auto_now=True, auto_now_add=False, verbose_name='Дата редактирования')

    def __str__(self):
        return "{}. Цена: {}".format(self.name, self.current_price)


    def get_absolute_url(self):
        return "/{}/{}".format(self.category.slug, self.slug)

cosmetic/forms.py
from django import forms


#  Форма авторизации пользователя на сайте
class LoginForm(forms.Form):
    exampleInputEmail1 = forms.EmailField()
    exampleInputPassword1 = forms.CharField(widget=forms.PasswordInput)

class RegisterForm(forms.Form):
    exampleInputEmail = forms.CharField(required=False)
    exampleInputPassword1 = forms.CharField(required=False)
    exampleInputPassword2 = forms.CharField(required=False)
    exampleInputName = forms.CharField(required=False)
    exampleInputLastName = forms.CharField(required=False)
    exampleInputMiddleName = forms.CharField(required=False)
    exampleInputPhone = forms.CharField(required=False)

cosmetic/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView, DetailView

from cart.forms import CartAddProductForm
from cosmetic.forms import LoginForm, RegisterForm
from cosmetic.models import Product, UserProfile


class HomePage(TemplateView):
    template_name = 'html/home.html'


    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['many_people_like_objects'] = Product.objects.all()[:3]
        context['many_people_like_objects'] = Product.objects.all()[:3]
        return context

class ProductView(DetailView):
    template_name = 'html/product_view.html'
    slug_url_kwarg = 'slug'
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart_product_form'] = CartAddProductForm()
        return context


class Login(TemplateView):
    template_name = 'html/sign-in/sign-in.html'

    def post(self, request, *args, **kwargs):
        if request.GET.get('submit', None) and request.GET.get('submit', None) == 'register':
            register_error = list()
            user = User()
            email = request.POST.get('exampleInputEmail', None)
            password1 = request.POST.get('exampleInputPassword1', None)
            password2 = request.POST.get('exampleInputPassword2', None)
            first_name = request.POST.get('exampleInputName', None)
            last_name = request.POST.get('exampleInputLastName', None)
            middle_name = request.POST.get('exampleInputMiddleName', None)
            phone = request.POST.get('exampleInputPhone', None)
            if email and not User.objects.filter(email=email).exists():
                user.email = email
                user.username = email
            else:
                register_error.append('Данный email уже зарегистрирован')
            if password1 == password2:
                user.password = password1
            else:
                register_error.append('Пароли не совпадают')
            if first_name:
                user.first_name = first_name
            if last_name:
                user.last_name = last_name
            if phone and UserProfile.objects.filter(phone=phone).exists():
                register_error.append('Данный телефон уже зарегистрирован')
            if not register_error:
                user.is_active = True
                user.save()
                login(request, user)
                user_profile = user.user_profile.create()
                if phone:
                    user_profile.phone = phone
                if middle_name:
                    user_profile.middle_name = middle_name
                user_profile.save()
            else:
                kwargs.update({'register_error': register_error})
                kwargs.update({'user_form': RegisterForm(initial={
                    'exampleInputEmail': email,
                    'exampleInputName': first_name,
                    'exampleInputLastName': last_name,
                    'exampleInputMiddleName': middle_name,
                    'exampleInputPhone': phone
                })})
        elif request.GET.get('submit', None) and request.GET.get('submit', None) == 'login':
            form = LoginForm(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                user = authenticate(username=cd['exampleInputEmail1'], password=cd['exampleInputPassword1'])
                if user is not None:
                    if user.is_active:
                        login(request, user)
                        kwargs.update({'successfully': 'Авторизация прошла успешно'})
                    else:
                        kwargs.update({'error': 'Аккаунт отключен'})
                else:
                    kwargs.update({'error': 'Неверный логин или пароль'})
        return super().get(request, *args, **kwargs)

cosmetic/templates/html/sign-in/sign-in.html
{% extends 'html/base/base.html' %}
{% load static %}
{% block title %}
Авторизация / регистрация
{% endblock %}
{% block body %}
<!-- ============================================== HEADER : END ============================================== -->
<div class="breadcrumb">
    <div class="container">
        <div class="breadcrumb-inner">
            <ul class="list-inline list-unstyled">
                <li><a href="{% url 'cosmetic:home_page' %}">Home</a></li>
                <li class='active'>Login</li>
            </ul>
        </div><!-- /.breadcrumb-inner -->
    </div><!-- /.container -->
</div><!-- /.breadcrumb -->

<div class="body-content">
    <div class="container">
        <div class="sign-in-page">
            <div class="row">
                <!-- Sign-in -->
                <div class="col-md-6 col-sm-6 sign-in">
                    <h4 class="">Войти на сайт</h4>
                    <p class="">Авторизация</p>
                    <div class="social-sign-in outer-top-xs">
                        <a href="#" class="facebook-sign-in"><i class="fa fa-facebook"></i> Войти через Facebook</a>
                        <a href="#" class="twitter-sign-in"><i class="fa fa-twitter"></i> Войти через Twitter</a>
                        <a href="/login/vk-oauth2"><img src="/static/lvk.png" class="avatar-3" data-toggle="tooltip" title="'Login via VKontakte'"></a>
                    </div>
                    {{ error }}
                    {{ successfully }}
                    <form class="register-form outer-top-xs" role="form" method="post" action="?submit=login">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="info-title" for="exampleInputEmail1">Email<span>*</span></label>
                            <input type="email" class="form-control unicase-form-control text-input"
                                   id="id_exampleInputEmail1" name="exampleInputEmail1">
                        </div>
                        <div class="form-group">
                            <label class="info-title" for="exampleInputPassword1">Пароль <span>*</span></label>
                            <input type="password" class="form-control unicase-form-control text-input"
                                   id="id_exampleInputPassword1" name="exampleInputPassword1">
                        </div>
                        <div class="radio outer-xs">
                            <label>
                                <input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">Запомнить меня!
                            </label>
                            <a href="#" class="forgot-password pull-right">Забыли пароль?</a>
                        </div>
                        <button type="submit" class="btn-upper btn btn-primary checkout-page-button">Войти</button>
                    </form>
                </div>
                <!-- Sign-in -->

                <!-- create a new account -->
                <div class="col-md-6 col-sm-6 create-new-account">
                    <h4 class="checkout-subtitle">Регистрация нового аккаунта</h4>
                    <p class="text title-tag-line">Создание нового аккаунта</p>
                    <div style="padding-top: 20px;">
                        {% if register_error %}
                            <ul>
                                {% for error in register_error %}
                                    <li style="color: red;">{{ error }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    </div>

                    <form class="register-form outer-top-xs" role="form" method="post" action="?submit=register">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="info-title" for="exampleInputName">Имя <span>*</span></label>
                            <input type="text" class="form-control unicase-form-control text-input"
                                   id="id_exampleInputName" name="exampleInputName" required
                                    {% if user_form.exampleInputName.value %}
                                        value="{{ user_form.exampleInputName.value }}"
                                    {% endif %}>
                        </div>
                        <div class="form-group">
                            <label class="info-title" for="exampleInputLastName">Фамилия <span>*</span></label>
                            <input type="text" class="form-control unicase-form-control text-input"
                                   id="id_exampleInputLastName" name="exampleInputLastName" required
                                    {% if user_form.exampleInputLastName.value %}
                                        value="{{ user_form.exampleInputLastName.value }}"
                                    {% endif %}>
                        </div>
                        <div class="form-group">
                            <label class="info-title" for="exampleInputMiddleName">Отчество <span>*</span></label>
                            <input type="text" class="form-control unicase-form-control text-input"
                                   id="id_exampleInputMiddleName" name="exampleInputMiddleName" required
                                    {% if user_form.exampleInputMiddleName.value %}
                                        value="{{ user_form.exampleInputMiddleName.value }}"
                                    {% endif %}>
                        </div>
                        <div class="form-group">
                            <label class="info-title" for="exampleInputPhone">Номер телефона<span>*</span></label>
                            <input type="text" class="form-control unicase-form-control text-input"
                                   id="id_exampleInputPhone" name="exampleInputPhone" required
                                    {% if user_form.exampleInputPhone.value %}
                                        value="{{ user_form.exampleInputPhone.value }}"
                                    {% endif %}>
                        </div>
                        <div class="form-group">
                            <label class="info-title" for="exampleInputEmail">Email<span>*</span></label>
                            <input type="email" class="form-control unicase-form-control text-input"
                                   id="id_exampleInputEmail" name="exampleInputEmail" required
                                    {% if user_form.exampleInputEmail.value %}
                                        value="{{ user_form.exampleInputEmail.value }}"
                                    {% endif %}>
                        </div>
                        <div class="form-group">
                            <label class="info-title" for="exampleInputPassword1">Пароль<span>*</span></label>
                            <input type="password" class="form-control unicase-form-control text-input"
                                   id="id_exampleInputPassword1" name="exampleInputPassword1" required>
                        </div>
                        <div class="form-group">
                            <label class="info-title" for="exampleInputPassword2">Пароль еще раз <span>*</span></label>
                            <input type="password" class="form-control unicase-form-control text-input"
                                   id="id_exampleInputPassword2" name="exampleInputPassword2" required>
                        </div>
                        <button type="submit" class="btn-upper btn btn-primary checkout-page-button">Зарегистрироваться</button>
                    </form>


                </div>
                <!-- create a new account -->            </div><!-- /.row -->
        </div><!-- /.sigin-in-->
    </div><!-- /.container -->
</div><!-- /.body-content -->


<!-- JavaScripts placed at the end of the document so the pages load faster -->
<script src="{% static 'assets/js/jquery-1.11.1.min.js' %}"></script>

<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>

<script src="{% static 'assets/js/bootstrap-hover-dropdown.min.js' %}"></script>
<script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>

<script src="{% static 'assets/js/echo.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.easing-1.3.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap-slider.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.rateit.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/lightbox.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap-select.min.js' %}"></script>
<script src="{% static 'assets/js/wow.min.js' %}"></script>
<script src="{% static 'assets/js/scripts.js' %}"></script>

<!-- For demo purposes – can be removed on production -->

{#<script src="{% static 'switchstylesheet/switchstylesheet.js' %}"></script>#}

<script>
    $(document).ready(function () {
        $(".changecolor").switchstylesheet({seperator: "color"});
        $('.show-theme-options').click(function () {
            $(this).parent().toggleClass('open');
            return false;
        });
    });

    $(window).bind("load", function () {
        $('.show-theme-options').delay(2000).trigger('click');
    });
</script>
<!-- For demo purposes – can be removed on production : End -->

{% endblock %}